# Database configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Load environment variables
  config:
    import: optional:file:.env[.properties]

# JWT configuration
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000


